name: Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: 84.54.47.28
          username: root
          key: Kirit

      - name: Copy code to server
        run: |
          scp -r ./* root@84.54.47.28:/HACK-THE-ICE-5.0

      - name: SSH Command
        uses: appleboy/ssh-action@master
        with:
          host: 84.54.47.28
          username: root
          key: Kirit
          port: 22
          script: |
            cd /HACK-THE-ICE-5.0
            docker-compose down
            docker-compose up -d
