name: Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: 84.54.47.28
          username: root
          key: 4yBx832jXwwQD3th

      - name: Copy code to server
        run: |
          scp -r ./* root@84.54.47.28:/path/to/your/app

      - name: SSH Command
        uses: appleboy/ssh-action@master
        with:
          host: 84.54.47.28
          username: root
          key: 4yBx832jXwwQD3th
          port: 22
          script: |
            cd /path/to/your/app
            docker-compose down
            docker-compose up -d
