name: Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: 84.54.47.28
          username: root
          key: -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDgMbpjiH
9ad1cCtYDwBkUcAAAAEAAAAAEAAAGXAAAAB3NzaC1yc2EAAAADAQABAAABgQDJGh4LD3j2
9752jHJC1hEpimouuTvc9on+106jQn7TmDPIKVIiWBNFUvIj4Osy0HTOCLBDxDnemKxCdS
Q22enQubP7UtIucSYbXOjLr7EEDZuyu1S07FywUxmFhfmht8xZv/U7UrVEqL3QHmHXVCPm
Infpj1moqExqOo8oK9dr5wcFK3iWcx1bm2fVu14q224Cf8pStjf82gG1r16zJ9gQaoX5BL
/3TJNM4ca03qnlzKcdYytQ8gwnjoRjcjBsUE8qWHMC8DCfyplNpQTIoK6VHdI6/vtTKnUr
n6SdtOyLdBPqWUnjm0dcIFk933jTTXPCycBhEBhQID5+9P2lxuOHPRmgptOASGkfqqiPaE
8kQQHbJKGxY9AwoXHNTegqhjCCK3KHH46xilh5mGTe7W/FkAi2ZTGUpXQ6FiuK/9eeivjM
ipL7xYkNbjk1m+wfPvGNzkyQGWK10vTXx9s29PK7OUrMzeqCrQtiD7ls/KYlX3hvH5n/dG
r7Z8Cs1gx6xJEAAAWgCLCQMZU9N2W3sDNUWKni527X+DkGTXzE5T3G6CgM/QsybbI0a0NQ
Qx0nHT+0ISq0npBWAHu5ND/5D89qwMYYDFPEcxQDTMk9oQit0zXVoEj1ifa0j1aRQDWhA8
k+Iqt+qJ9ngq9/NiliFVZXWJUTjAKf4NytoeWreimlXj3kwftVYghb0Ej9ok8p/f0o0V6i
60LGkZU56S0ON3WqWoGqtefhvGC/3lyqPsdJ2KHr7DOe8k3xuw7+CGPcv9w76niGuEHO0+
hYccrmCPLLPFA2oLNg+TxcAgB03kqkZ2rSGz+snhlOAAmMX9T+/kyFWl8+M0kqXZFi8lVf
MJUlmuXEkeRYh2pjUo1dw/2mm+T+x1sbCkslRSbWSYvbxsiHC3ZvS22xq4kSzIsodiVJG2
i1tyseQEnFOhplTPmclwFayp0P9unU/liATirb1W+PjUbltShFhMpjuh7oyZxqx3HoJKs5
eTxpzzi7ukTqU2q8hD8XgMlzvYTBFybvY4pM5VW9uK1x5CdwiJgQq6Yahy/hygngTz8z9Z
tHvpMHS9pJXwkL3uCzbyf4a2TuM/V1s8cdk1/G9S3mw2+yz8No/pBEE7YK5yjokEwmOhnU
hMPkTvZPmnu87TZn9oe3yITjJKYS4tboFFEY1Q1tQu3bpFr7+KNRLlKTMhZ5DJPrbdvfKe
rUe8Lw7m9PfghjJnaJt4uQDRu/0OYoZ8CBFx5H9LRojNqIm23Fwn/vv/uslQfg0pHgh/UU
uQ4kR0BHSYzDWC/X+m2O+nWnDA4+ueJOqbpSU0e29O5Vmu7d1ADr0GR/C6eff0FD62ucnr
aW/YVuNMdHQhZMuQpLK4QnJEYy9yHdzxYQBzfdJX3I+ajsC7Itq2IAFefdNdFV9N9VJNHD
xNwHtxy36M69+7pyTR6WgJgtmP0e4xbbfYBXmAU6FREPHq89t3txDDlb++Jfj5n6vS5RXH
vs8XA3GqB4yXUEsa9aMuwEMNu0/e2sshBm8GCAuc0ZxIydSWHj0wNcd+H2panivNu9+/Fl
Adyt/C4DUdes3gmMkKgJvUoIB+5/L8Qnf3q9eDjtHvjRrkA8bETwpu8YvTBSW8Ub4mBQHq
XBVnBbZI7qQCdeZc/qIGDJtae9Xhv10Is92USlXZfgmKP1OMzeUW9faCwYc/6d8kJtUUcQ
6bIeww9os7WEjhM2Q0/m0cJgHwJuffYuuTYp4VBCBcJ6LUwvwV7vusUQQJX9vWmg5ndcHP
YiqONir/4pfXY2tsExMYbTL2SPNDCdbANO+6LN/+VpzZZMuLMlSNGDsJ2Rl1bXsY8ex1sL
fftj+23GJwtHts3BsPikCsaWNssqHVe2R6cloQT2xE8rNjswMis86+7Ma8UbrLKvM9wbnY
s6hChcNw77RprioZ+7EajVTPTocGGjYozk9X1rps71ODkLLOlkZdj8N4ik5TCzYpHSK86M
kWRnmvopGNbd2athX0N8jpcpYE3aq3lTdBOiIFOOONIxbXVuj1oH/0ka7N8MWC30lR8qeG
VWTUH+eSfsMJTnfk0PHrXxIqs77LOvLLQHuR95i2BANeb1Jnt3Nom5EVemy5yOlkL2nG/s
z4uqWogmKLbup20BjWu40dnso+zAD2p+tZ/pFn2ErF0j5CklesZ0wm9+jTkpzo9vI7VZBA
GC0CHrY1iCW3hmYRPd8F/6xGkBvykBhpPkOV9m5zoac/XI6pG0vJcLJr/6wiJzb7mGJ13t
uve8y1LLMSyWXRue9j9k94TB0VH/1NiF4fWakxvvG3JyiuXyTo1ZzPLzoandqUbdw5QD0r
5tj4Cqh0FEnNa2MNJJnpdM0SUx0XJO6WpNJMAK/e7ZojsxrzzdbHtKYCVOM63Orz6TjSVr
y6l7qjs3bpm1ug/6adcdVjvvhfd10w6mn3Rkv0xiGzhmn4/K
-----END OPENSSH PRIVATE KEY-----
 
          
          

      - name: Copy code to server
        run: |
          scp -r ./* root@84.54.47.28:/HACK-THE-ICE-5.0

      - name: SSH Command
        uses: appleboy/ssh-action@master
        with:
          host: 84.54.47.28
          username: root
          key: -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDgMbpjiH
9ad1cCtYDwBkUcAAAAEAAAAAEAAAGXAAAAB3NzaC1yc2EAAAADAQABAAABgQDJGh4LD3j2
9752jHJC1hEpimouuTvc9on+106jQn7TmDPIKVIiWBNFUvIj4Osy0HTOCLBDxDnemKxCdS
Q22enQubP7UtIucSYbXOjLr7EEDZuyu1S07FywUxmFhfmht8xZv/U7UrVEqL3QHmHXVCPm
Infpj1moqExqOo8oK9dr5wcFK3iWcx1bm2fVu14q224Cf8pStjf82gG1r16zJ9gQaoX5BL
/3TJNM4ca03qnlzKcdYytQ8gwnjoRjcjBsUE8qWHMC8DCfyplNpQTIoK6VHdI6/vtTKnUr
n6SdtOyLdBPqWUnjm0dcIFk933jTTXPCycBhEBhQID5+9P2lxuOHPRmgptOASGkfqqiPaE
8kQQHbJKGxY9AwoXHNTegqhjCCK3KHH46xilh5mGTe7W/FkAi2ZTGUpXQ6FiuK/9eeivjM
ipL7xYkNbjk1m+wfPvGNzkyQGWK10vTXx9s29PK7OUrMzeqCrQtiD7ls/KYlX3hvH5n/dG
r7Z8Cs1gx6xJEAAAWgCLCQMZU9N2W3sDNUWKni527X+DkGTXzE5T3G6CgM/QsybbI0a0NQ
Qx0nHT+0ISq0npBWAHu5ND/5D89qwMYYDFPEcxQDTMk9oQit0zXVoEj1ifa0j1aRQDWhA8
k+Iqt+qJ9ngq9/NiliFVZXWJUTjAKf4NytoeWreimlXj3kwftVYghb0Ej9ok8p/f0o0V6i
60LGkZU56S0ON3WqWoGqtefhvGC/3lyqPsdJ2KHr7DOe8k3xuw7+CGPcv9w76niGuEHO0+
hYccrmCPLLPFA2oLNg+TxcAgB03kqkZ2rSGz+snhlOAAmMX9T+/kyFWl8+M0kqXZFi8lVf
MJUlmuXEkeRYh2pjUo1dw/2mm+T+x1sbCkslRSbWSYvbxsiHC3ZvS22xq4kSzIsodiVJG2
i1tyseQEnFOhplTPmclwFayp0P9unU/liATirb1W+PjUbltShFhMpjuh7oyZxqx3HoJKs5
eTxpzzi7ukTqU2q8hD8XgMlzvYTBFybvY4pM5VW9uK1x5CdwiJgQq6Yahy/hygngTz8z9Z
tHvpMHS9pJXwkL3uCzbyf4a2TuM/V1s8cdk1/G9S3mw2+yz8No/pBEE7YK5yjokEwmOhnU
hMPkTvZPmnu87TZn9oe3yITjJKYS4tboFFEY1Q1tQu3bpFr7+KNRLlKTMhZ5DJPrbdvfKe
rUe8Lw7m9PfghjJnaJt4uQDRu/0OYoZ8CBFx5H9LRojNqIm23Fwn/vv/uslQfg0pHgh/UU
uQ4kR0BHSYzDWC/X+m2O+nWnDA4+ueJOqbpSU0e29O5Vmu7d1ADr0GR/C6eff0FD62ucnr
aW/YVuNMdHQhZMuQpLK4QnJEYy9yHdzxYQBzfdJX3I+ajsC7Itq2IAFefdNdFV9N9VJNHD
xNwHtxy36M69+7pyTR6WgJgtmP0e4xbbfYBXmAU6FREPHq89t3txDDlb++Jfj5n6vS5RXH
vs8XA3GqB4yXUEsa9aMuwEMNu0/e2sshBm8GCAuc0ZxIydSWHj0wNcd+H2panivNu9+/Fl
Adyt/C4DUdes3gmMkKgJvUoIB+5/L8Qnf3q9eDjtHvjRrkA8bETwpu8YvTBSW8Ub4mBQHq
XBVnBbZI7qQCdeZc/qIGDJtae9Xhv10Is92USlXZfgmKP1OMzeUW9faCwYc/6d8kJtUUcQ
6bIeww9os7WEjhM2Q0/m0cJgHwJuffYuuTYp4VBCBcJ6LUwvwV7vusUQQJX9vWmg5ndcHP
YiqONir/4pfXY2tsExMYbTL2SPNDCdbANO+6LN/+VpzZZMuLMlSNGDsJ2Rl1bXsY8ex1sL
fftj+23GJwtHts3BsPikCsaWNssqHVe2R6cloQT2xE8rNjswMis86+7Ma8UbrLKvM9wbnY
s6hChcNw77RprioZ+7EajVTPTocGGjYozk9X1rps71ODkLLOlkZdj8N4ik5TCzYpHSK86M
kWRnmvopGNbd2athX0N8jpcpYE3aq3lTdBOiIFOOONIxbXVuj1oH/0ka7N8MWC30lR8qeG
VWTUH+eSfsMJTnfk0PHrXxIqs77LOvLLQHuR95i2BANeb1Jnt3Nom5EVemy5yOlkL2nG/s
z4uqWogmKLbup20BjWu40dnso+zAD2p+tZ/pFn2ErF0j5CklesZ0wm9+jTkpzo9vI7VZBA
GC0CHrY1iCW3hmYRPd8F/6xGkBvykBhpPkOV9m5zoac/XI6pG0vJcLJr/6wiJzb7mGJ13t
uve8y1LLMSyWXRue9j9k94TB0VH/1NiF4fWakxvvG3JyiuXyTo1ZzPLzoandqUbdw5QD0r
5tj4Cqh0FEnNa2MNJJnpdM0SUx0XJO6WpNJMAK/e7ZojsxrzzdbHtKYCVOM63Orz6TjSVr
y6l7qjs3bpm1ug/6adcdVjvvhfd10w6mn3Rkv0xiGzhmn4/K
-----END OPENSSH PRIVATE KEY-----

          port: 22
          script: |
            cd /HACK-THE-ICE-5.0
            docker-compose down
            docker-compose up -d
